FROM registry.redhat.io/ubi9/go-toolset:9.7@sha256:6983c6e7023236d1b5093c75c94402c7bdfd43c36ed9c34f2feda72a0ea7c8b1 AS builder

USER 0
WORKDIR /app

ENV GOTOOLCHAIN=auto

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ cmd/
COPY pkg/ pkg/
COPY internal/ internal/

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /usr/local/bin/model-signing ./cmd/model-signing

FROM registry.access.redhat.com/ubi9-minimal@sha256:bb08f2300cb8d12a7eb91dddf28ea63692b3ec99e7f0fa71a1b300f2756ea829 AS deploy

COPY --from=builder /usr/local/bin/model-signing /usr/local/bin/model-signing
COPY LICENSE /licenses/license.txt

USER 65532:65532

ENTRYPOINT ["model-signing"]
CMD ["--help"]

LABEL description="Supply chain security for ML"
LABEL io.k8s.description="Supply chain security for ML"
LABEL io.k8s.display-name="Model Transparency Library"
LABEL io.openshift.tags="model transparency security ml"
LABEL summary="Provides a library for model transparency."
LABEL com.redhat.component="model-transparency"
LABEL name="rhtas/model-transparency-rhel9"
LABEL cpe="cpe:/a:redhat:trusted_artifact_signer:1.3.1::el9"
